### ISSUE TITLE
多个producer或者consumer如何创建

### ISSUE THREAD

**Issue by klaus-pd** [hiwepy/rocketmq-plus-spring-boot-starter#3]
1。如有一个jvm中创建多个producer或consumer如何创建
2.看配置中有一个installName的参数，是用来配置spring生成的bean的name吗？
  @Autowired
    @Qualifier(value = "abc")
    private DefaultMQProducer defaultProducer;

这样的方式无法获取defaultProducer对象。去掉@Qualifier(value = "abc")是没有问题的。

**Comment by vindell** [comment]
在使用rocketmq时发现有个规定，同一个consumer-group下面不能订阅多个主题，考虑单个JVM性能问题，我在实现该starter时候，默认仅会创建单个DefaultMQProducer 、MQPushConsumer、MQPullConsumer；后期会考虑增加，多生产者，多消费者；

@Bean
	@ConditionalOnProperty(prefix = RocketmqProducerProperties.PREFIX, value = "producerGroup")
	public DefaultMQProducer defaultProducer(RocketmqProducerProperties properties,
			TransactionCheckListener transactionCheckListener) throws MQClientException {
}

@Bean
@ConditionalOnMissingBean
public DefaultMQPushConsumer pushConsumer(RocketmqPushConsumerProperties properties,
			@Autowired(required = false) OffsetStore offsetStore,
			@Autowired(required = false) SubscriptionProvider subProvider,
			MessageListenerOrderly messageListenerOrderly,
			MessageListenerConcurrently messageListenerConcurrently,
			AllocateMessageQueueStrategy allocateMessageQueueStrategy) throws MQClientException {
}

@Bean
@ConditionalOnMissingBean
public DefaultMQPullConsumer pullConsumer(RocketmqPullConsumerProperties properties,
			AllocateMessageQueueStrategy allocateMessageQueueStrategy) throws MQClientException {
}

#instanceName 是 Rocketmq 内置的参数
 private String instanceName = System.getProperty("rocketmq.client.name", "DEFAULT");

用于构建客户唯一标示：

 public String buildMQClientId() {
        StringBuilder sb = new StringBuilder();
        sb.append(this.getClientIP());

        sb.append("@");
        sb.append(this.getInstanceName());
        if (!UtilAll.isBlank(this.unitName)) {
            sb.append("@");
            sb.append(this.unitName);
        }

        return sb.toString();
    }
